### ISSUE TITLE
Task 2 (Use Cases)

### ISSUE THREAD

**Issue by parmis-sadeghi** [parmis-sadeghi/Job-opportunities-web-application#2]
-Draw an Activity diagram (An activity diagram visually presents a series of actions or flow of
control in a system similar to a flowchart or a data flow diagram)

**Comment by kianazndb** [comment]
[Uploading activity diagrams.pdf…]()

**Comment by kianazndb** [comment]
[Uploading activity diagrams.pdf…]()

**Comment by kianazndb** [comment]
[Uploading activity diagrams.pdf…]()
