### ISSUE TITLE
Task 5 (DataBase Design)

### ISSUE THREAD

**Issue by parmis-sadeghi** [parmis-sadeghi/Job-opportunities-web-application#5]
-After defining your use cases and actors and design patterns, use UML or ERD (optional) to
illustrate your DataBase (you can use draw.io, rational rose, dbdiagram.io, QuickDBD …)
-Choose a Relational database management system (MySQL, SQL-lite, PostgreSQL, Redis,
etc) for your project and explain why did you choose it (Both SQL and NoSQL databases are
allowed)

**Comment by Asal-shakeri** [comment]
![IMG_0778](https://github.com/parmis-sadeghi/Job-opportunities-web-application/assets/109144165/1c205349-ce60-4395-b4fc-93e293c99a18)
[Relational database management system.pdf](https://github.com/parmis-sadeghi/Job-opportunities-web-application/files/13496387/Relational.database.management.system.pdf)

**Comment by Asal-shakeri** [comment]
.
